### ISSUE TITLE
Feature request: Additional LB stats from `show load-balance status`

### ISSUE THREAD

**Issue by joeshaw** [chitoku-k/edgerouter-exporter#157]
`show load-balance watchdog` pulls good metrics for the current state of the health of the load balancer, but it would be nice if it pulled additional data from `show load-balance status`:

```
$ show load-balance status
Group G
    Balance Local  : true
    Lock Local DNS : false
    Conntrack Flush: true
    Sticky Bits    : 0x00000000

  interface   : eth8
  reachable   : true
  status      : failover
  gateway     : x.x.x.x
  route table : 201
  weight      : 0%
  fo_priority : 60
  flows
      WAN Out   : 0
      WAN In    : 0
      Local ICMP: 2342
      Local DNS : 0
      Local Data: 0

  interface   : eth9
  reachable   : true
  status      : active
  gateway     : y.y.y.y
  route table : 202
  weight      : 100%
  fo_priority : 100
  flows
      WAN Out   : 164K
      WAN In    : 1
      Local ICMP: 2344
      Local DNS : 0
      Local Data: 2524
```

In particular, I'd like to know `reachable` (though maybe that's the same as `edgerouter_load_balancer_health`), `status`, `gateway`, `weight`, and flow data.

**Comment by chitoku-k** [comment]
Correct me if I am missing something, but at first glance, `reachable`, `status`, and `gateway` are already available in:

- `reachable`: equivalent to `edgerouter_load_balancer_ping_health`
- `status`: mostly equivalent to `edgerouter_load_balancer_health`
  - Is `failover` indicated by `show load-balance status` helpful as a metric?
- `gateway`: equivalent to the `gateway` label on `edgerouter_load_balancer_ping_health`

On the other hand, the `weight` and flow data seem to be worth adding. What do you think of good metrics from the stats? I am currently thinking of the following:

```
edgerouter_load_balancer_weight_ratio{group_name="G",interface_name="eth8"} 0
edgerouter_load_balancer_weight_ratio{group_name="G",interface_name="eth9"} 1
```

```
edgerouter_load_balancer_flows_total{group_name="G",interface_name="eth8",flow="WAN Out"} 0
edgerouter_load_balancer_flows_total{group_name="G",interface_name="eth9",flow="WAN Out"} 164000
edgerouter_load_balancer_flows_total{group_name="G",interface_name="eth8",flow="WAN In"} 0
edgerouter_load_balancer_flows_total{group_name="G",interface_name="eth9",flow="WAN In"} 1
...
```

**Comment by joeshaw** [comment]
`failover` is particularly helpful to me as I have two WAN connections and would like to know which one is currently active.  (I don't actually load balance between them, just fail over from one to the other if the primary fails).  In typical operation, `edgerouter_load_balancer_health` is 1 for both interfaces, which doesn't convey this information.

`gateway` in `edgerouter_load_balancer_ping_health` I think is a misnomer.  For me, it is the ping target, and I use `8.8.8.8` for that, not my actual gateway.  The `gateway` label in `show load-balance status` is my actual gateway.

I think your example for the weight ratio makes sense.  I assume it'll be a value between 0 and 1?

Flow stats look good to me.

**Comment by chitoku-k** [comment]
Thanks for clarification.

> In typical operation, `edgerouter_load_balancer_health` is 1 for both interfaces, which doesn't convey this information.  Perhaps the weight ratio could serve that purpose, however.

As far as I quickly tested this, the combination of `edgerouter_load_balancer_health` and the new `edgerouter_load_balancer_weight_ratio` seems to do the job here; however, adding `edgerouter_load_balancer_status` that directly indicates failover status makes sense to me as well. Note when both of the configured interfaces are down, both interfaces show `inactive` as their statuses, which could be somehow used for monitoring.

Probably the status is one of the `inactive`, `active`, and `failover` which could be mapped to 0-2 respectively like:

```
edgerouter_load_balancer_status{group_name="G",interface_name="eth8"} 2
edgerouter_load_balancer_status{group_name="G",interface_name="eth9"} 1
```

>` gateway` in `edgerouter_load_balancer_ping_health` I think is a misnomer.  For me, it is the ping target, and I use `8.8.8.8` for that, not my actual gateway.  The `gateway` label in `show load-balance status` is my actual gateway.

I understand what's going on but then where is that gateway configured? I don't find any similar configuration under `load-balance`. Also I am reluctant to add metrics that aren't dynamic; I confirmed that the `status` and `weight` are dynamic.

![image](https://user-images.githubusercontent.com/6535425/187181218-683b151c-3b6a-459b-8f1f-c1126a86534a.png)

> I think your example for the weight ratio makes sense. I assume it'll be a value between 0 and 1?

Yes.

**Comment by joeshaw** [comment]
> Probably the status is one of the inactive, active, and failover which could be mapped to 0-2 respectively

👍 I like this.

> I understand what's going on but then where is that gateway configured? I don't find any similar configuration under load-balance. Also I am reluctant to add metrics that aren't dynamic; I confirmed that the status and weight are dynamic.

This is what my config looks like for load-balance:

```
# show load-balance
 group G {
     exclude-local-dns disable
     flush-on-active enable
     gateway-update-interval 20
     interface eth8 {
         failover-only
         route-test {
             initial-delay 60
             interval 10
             type {
                 ping {
                     target 8.8.8.8
                 }
             }
         }
     }
     interface eth9 {
         route-test {
             initial-delay 60
             interval 10
             type {
                 ping {
                     target 8.8.8.8
                 }
             }
         }
     }
     lb-local enable
     lb-local-metric-change enable
 }
```

**Comment by chitoku-k** [comment]
The `gateway` field looks like it's fulfilled when `lb-local` is enabled and empty otherwise:

```
admin@ubnt:~$ configure
[edit]
admin@ubnt# show load-balance group WAN_FAILOVER lb-local
 lb-local disable
```

```
admin@ubnt:~$ show load-balance status
Group WAN_FAILOVER
    Balance Local  : false
    Lock Local DNS : false
    Conntrack Flush: false
    Sticky Bits    : 0x00000000

  interface   : eth0
  reachable   : true
  status      : failover
  gateway     :
  route table : 1
  weight      : 0%
  fo_priority : 60
  flows
      WAN Out   : 4
      WAN In    : 1
      Local ICMP: 10990
      Local DNS : 0
      Local Data: 0

  interface   : switch0
  reachable   : true
  status      : active
  gateway     :
  route table : 2
  weight      : 100%
  fo_priority : 100
  flows
      WAN Out   : 84795
      WAN In    : 49702
      Local ICMP: 11023
      Local DNS : 0
      Local Data: 0
```

I don't think it's a good metric as this is more like configuration rather than metrics.

**Comment by chitoku-k** [comment]
Some additional LB stats have been added in v2.7.0. Hope it helps!
