### ISSUE TITLE
wrong ip_address label on edgerouter_pppoe_client_session_.* 

### ISSUE THREAD

**Issue by sosomasox** [chitoku-k/edgerouter-exporter#63]
Thank you for your quick [this bug](https://github.com/chitoku-k/edgerouter-exporter/issues/60) fix!!! 

I want to get current using IP address from ip_address label on "edgerouter_pppoe_client_session_.*".

But unfortunately, I get a different IP address from currently using.

If you have a time, please consider to solve it.

**Comment by sosomasox** [comment]
It appear to get IP address that executing "show pppoe-client" command.

True IP address is different when executing "show pppoe-client" command.
I want to get a IP address on pppoe0 interface shown Web dash board.

**Comment by sosomasox** [comment]
I found a solution!
"show interfaces | grep pppoe" command is able to return current use IP address.

**Comment by chitoku-k** [comment]
Thanks again for pointing out. For PPPoE sessions, the values on the Web UI indicates the local IP address while the command output from `show pppoe-client` shows the remote IP address as its column name states. You can confirm this by `ip addr show` to find both of them shown. I'll try to find some way to probably export both IP addresses on that metric.

**Comment by chitoku-k** [comment]
Now `local_ip_address` label is added to `pppoe_client_session_*` metrics that is the same one as in the Web UI. Please check out v2.1.0 🎉

**Comment by sosomasox** [comment]
I'm glad to hear that announcement!!!
I have used the new release version, it is really wanted one!

Thank you for your effort.
